In [3]:
### <h2 style="color: Yellow;">Numpy Part 2</h2>
import numpy as np  # Importing NumPy

# **NumPy** (Numerical Python) is an open-source Python library that's widely used in science and engineering.
# The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray,
# and a large library of functions that operate efficiently on these data structures.

## **<h2 style="color: Yellow;">Why use NumPy?</h2>**
# Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain 
# elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

# Depending on the characteristics of the data and the types of operations that need to be performed, 
# other containers may be more appropriate; by exploiting these characteristics, we can improve speed, reduce memory 
# consumption, and offer a high-level syntax for performing a variety of common processing tasks. 
# NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

## **<h2 style="color: Yellow;">What is an “array”?</h2>**
# In computer programming, an array is a structure for storing and retrieving data. 
# We often talk about an array as if it were a grid in space, with each cell storing one element of the data.

# Most NumPy arrays have some restrictions:
# - All elements of the array must be of the same type of data.
# - Once created, the total size of the array can’t change.
# - The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

# How to import NumPy
array = np.array([1, 2, 3, 4, 5])
print(array)  # Show the elements of the array

# **Find Specific Element in array using index**
# Index starts from 0
# Note: NumPy arrays are “0-indexed”: the first element of the array is accessed using index 0.

print(array[0])  # Show the first value in the array using index

# The array is mutable; you can add elements like:
array[0] = 10
print(array)

# You can access the first 3 elements in the array
print(array[:3])  # Access the first 3 elements in the array

## 2D Array
two_d_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])  # Create a 2D array
print(two_d_array)

# Check the dimension of the array
print(two_d_array.ndim)  # Number of dimensions

# Check the size of the array
print(two_d_array.size)  # Total number of elements in the array

# Check the length of the array
print(len(two_d_array))  # Number of rows

# Access an element in a 2D array
print(two_d_array[0, 2])  # Access the 3rd element of the first row

## 3D Array
three_d_array = np.array([[[1, 2, 3, 4, 5]], [[6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15]]])
print(three_d_array)
print(three_d_array.ndim)

## **Array attributes**
# The number of dimensions of an array is contained in the ndim attribute.
array = np.array([1, 2, 3, 4, 5, 6])  # One-dimensional array
print(array.ndim)  # Number of dimensions

# Check the shape
print(array.shape)  # Shape of the array

# Check the length
print(len(array))  # Length of the array

array_1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array_1.shape)  # Shape of the 2D array
print(len(array_1.shape) == array_1.ndim)  # Check if shape length equals number of dimensions
print(array_1.dtype)  # Data type of the array

## How to create a basic array
# Creating arrays filled with 0’s or 1’s
print(np.zeros(2))  # Array with 0 elements
print(np.ones(2))   # Array with 1 elements

x = np.arange(23)  # Create an array using range
print(x)

array_2d = np.arange(12).reshape(2, 6)  # Reshape into 2D
print(array_2d)

# Array of even numbers from 0 to 23
even = np.arange(0, 24, 2)
print(even)

# Array of odd numbers from 0 to 23
odd = np.arange(0, 24, 2)
print(odd)

# Create an array with values that are spaced linearly in a specified interval
print(np.linspace(0, 10, num=5))  # 5 values between 0 and 10

## Specifying your data type
# Explicitly specify the data type
x = np.ones(2, dtype=np.int32)  # Change data type to int
print(x)

x = np.ones(2, dtype=np.float32)  # Change data type to float
print(x)

## Adding, removing, and sorting elements
array = np.array([2, 4, 8, 6, 5, 9, 10])  # Unsorted array
print(array)

sorted_array = np.sort(array)  # Sort the array in ascending order
print(sorted_array)

# How to add arrays using `np.concatenate()`
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9, 10])
concated_ab = np.concatenate((a, b))  # Concatenate two arrays
print(concated_ab)

# Concatenating 2D arrays
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])
print(np.concatenate((a, b), axis=0))  # Row-wise concatenation
print(np.concatenate((a, b), axis=1))  # Column-wise concatenation

# Adding elements to an array
array = np.array([1, 2, 3, 4])
array = np.append(array, 5)  # Append a new element
print(array)

## **How do you know the shape and size of an array?**
array = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                  [[9, 10, 11, 12], [13, 14, 15, 16]],
                  [[17, 18, 19, 20], [21, 22, 23, 24]]])  # 3D array
print(array.ndim)  # Dimensions
print("The shape of array is ", array.shape)  # Shape
print("The Total size of array is ", array.size)  # Total number of elements

## **`Reshape an array`**
a = np.arange(6)  # 1D array
b = a.reshape(2, 3)  # Reshape to 2 rows, 3 columns
print(b)

# Create an array with 6 elements
a = np.arange(6)
print("Original array:")
print(a)

# Reshape the array to 2 rows and 3 columns
reshaped_a = np.reshape(a, (2, 3), order='c')
print("\nReshaped array (2, 3):")
print(reshaped_a)

## <h2 style="color: Yellow;"> How to convert a 1D array into a 2D array (how to add a new axis to an array)</h2>
array = np.arange(6)
array2 = array[np.newaxis, :]  # Add a new axis
print(array2.shape)

# Using np.expand_dims to add an axis
c = np.expand_dims(array, axis=1)
print(c.shape)

## <h2 style ="color:yellow;"> Indexing and slicing </h2>
data = np.array([1, 2, 3, 5, 6, 7, 8, 9])
print("We can access index-wise values:", data[1])  # Access value at index 1
print(data[0:2])  # Print values from index 0 to 2
print(data[1:])  # Print all values after index 1
print(data[-1])  # Access last value

[1 2 3 4 5]
1
[10  2  3  4  5]
[10  2  3]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
10
2
3
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]

 [[11 12 13 14 15]]]
3
1
(6,)
6
(2, 5)
True
int64
[0. 0.]
[1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 0.   2.5  5.   7.5 10. ]
[1 1]
[1. 1.]
[ 2  4  8  6  5  9 10]
[ 2  4  5  6  8  9 10]
[ 1  2  3  4  5  5  6  7  8  9 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]
[1 2 3 4 5]
3
The shape of array is  (3, 2, 4)
The Total size of array is  24
[[0 1 2]
 [3 4 5]]
Original array:
[0 1 2 3 4 5]

Reshaped array (2, 3):
[[0 1 2]
 [3 4 5]]
(1, 6)
(6, 1)
We can access index-wise values: 2
[1 2]
[2 3 5 6 7 8 9]
9
